from api.models import Strategy

class StrategyCreator:
  def __init__(self, coin, **kwargs):
    self.coin = coin

  def create(self):
    for strategy_data in self.strategy_list():
      Strategy.objects.create(**strategy_data)

  def strategy_list(self):
    return [
      { "name": "Strategy 1", "rsi_type": "6", "rsi_time": "1m", "coin_id": self.coin, "buy_at": 30, "sell_at": 70, "order": 1, "expected_time": "1 hour", "expected_percentage": "0.25%" },
      { "name": "Strategy 2", "rsi_type": "6", "rsi_time": "1m", "coin_id": self.coin, "buy_at": 20, "sell_at": 70, "order": 2, "expected_time": "1 hour", "expected_percentage": "0.25%" },
      { "name": "Strategy 3", "rsi_type": "6", "rsi_time": "1m", "coin_id": self.coin, "buy_at": 10, "sell_at": 70, "order": 3, "expected_time": "1 hour", "expected_percentage": "0.25%" },
      { "name": "Strategy 4", "rsi_type": "14", "rsi_time": "1m", "coin_id": self.coin, "buy_at": 30, "sell_at": 70, "order": 4, "expected_time": "1 hour", "expected_percentage": "0.45%" },
      { "name": "Strategy 5", "rsi_type": "14", "rsi_time": "1m", "coin_id": self.coin, "buy_at": 20, "sell_at": 70, "order": 5, "expected_time": "1 hour", "expected_percentage": "0.45%" },
      { "name": "Strategy 6", "rsi_type": "14", "rsi_time": "1m", "coin_id": self.coin, "buy_at": 10, "sell_at": 70, "order": 6, "expected_time": "1 hour", "expected_percentage": "0.45%" },
      { "name": "Strategy 7", "rsi_type": "6", "rsi_time": "3m", "coin_id": self.coin, "buy_at": 30, "sell_at": 70, "order": 7, "expected_time": "3 hours", "expected_percentage": "0.45%" },
      { "name": "Strategy 8", "rsi_type": "6", "rsi_time": "3m", "coin_id": self.coin, "buy_at": 20, "sell_at": 70, "order": 8, "expected_time": "3 hours", "expected_percentage": "0.45%" },
      { "name": "Strategy 9", "rsi_type": "6", "rsi_time": "3m", "coin_id": self.coin, "buy_at": 10, "sell_at": 70, "order": 9, "expected_time": "3 hours", "expected_percentage": "0.45%" },
      { "name": "Strategy 10", "rsi_type": "14", "rsi_time": "3m", "coin_id": self.coin, "buy_at": 30, "sell_at": 70, "order": 10, "expected_time": "3 hours", "expected_percentage": "1%" },
      { "name": "Strategy 11", "rsi_type": "14", "rsi_time": "3m", "coin_id": self.coin, "buy_at": 20, "sell_at": 70, "order": 11, "expected_time": "3 hours", "expected_percentage": "1%" },
      { "name": "Strategy 12", "rsi_type": "14", "rsi_time": "3m", "coin_id": self.coin, "buy_at": 10, "sell_at": 70, "order": 12, "expected_time": "3 hours", "expected_percentage": "1%" },
      { "name": "Strategy 13", "rsi_type": "6", "rsi_time": "5m", "coin_id": self.coin, "buy_at": 30, "sell_at": 70, "order": 13, "expected_time": "5 hours", "expected_percentage": "2%" },
      { "name": "Strategy 14", "rsi_type": "6", "rsi_time": "5m", "coin_id": self.coin, "buy_at": 20, "sell_at": 70, "order": 14, "expected_time": "5 hours", "expected_percentage": "2%" },
      { "name": "Strategy 15", "rsi_type": "6", "rsi_time": "5m", "coin_id": self.coin, "buy_at": 10, "sell_at": 70, "order": 15, "expected_time": "5 hours", "expected_percentage": "2%" },
      { "name": "Strategy 16", "rsi_type": "14", "rsi_time": "5m", "coin_id": self.coin, "buy_at": 30, "sell_at": 70, "order": 16, "expected_time": "5 hours", "expected_percentage": "3%" },
      { "name": "Strategy 17", "rsi_type": "14", "rsi_time": "5m", "coin_id": self.coin, "buy_at": 20, "sell_at": 70, "order": 17, "expected_time": "5 hours", "expected_percentage": "3%" },
      { "name": "Strategy 18", "rsi_type": "14", "rsi_time": "5m", "coin_id": self.coin, "buy_at": 10, "sell_at": 70, "order": 18, "expected_time": "5 hours", "expected_percentage": "3%" },
      { "name": "Strategy 19", "rsi_type": "6", "rsi_time": "15m", "coin_id": self.coin, "buy_at": 30, "sell_at": 70, "order": 19, "expected_time": "24 hours", "expected_percentage": "2.5%" },
      { "name": "Strategy 20", "rsi_type": "6", "rsi_time": "15m", "coin_id": self.coin, "buy_at": 20, "sell_at": 70, "order": 20, "expected_time": "24 hours", "expected_percentage": "2.5%" },
      { "name": "Strategy 21", "rsi_type": "6", "rsi_time": "15m", "coin_id": self.coin, "buy_at": 10, "sell_at": 70, "order": 21, "expected_time": "24 hours", "expected_percentage": "2.5%" },
      { "name": "Strategy 22", "rsi_type": "14", "rsi_time": "15m", "coin_id": self.coin, "buy_at": 30, "sell_at": 70, "order": 22, "expected_time": "24 hours", "expected_percentage": "3.5%" },
      { "name": "Strategy 23", "rsi_type": "14", "rsi_time": "15m", "coin_id": self.coin, "buy_at": 20, "sell_at": 70, "order": 23, "expected_time": "24 hours", "expected_percentage": "3.5%" },
      { "name": "Strategy 24", "rsi_type": "14", "rsi_time": "15m", "coin_id": self.coin, "buy_at": 10, "sell_at": 70, "order": 24, "expected_time": "24 hours", "expected_percentage": "3.5%" },
      { "name": "Strategy 25", "rsi_type": "6", "rsi_time": "30m", "coin_id": self.coin, "buy_at": 30, "sell_at": 70, "order": 25, "expected_time": "20 hours", "expected_percentage": "4%" },
      { "name": "Strategy 26", "rsi_type": "6", "rsi_time": "30m", "coin_id": self.coin, "buy_at": 20, "sell_at": 70, "order": 26, "expected_time": "20 hours", "expected_percentage": "4%" },
      { "name": "Strategy 27", "rsi_type": "6", "rsi_time": "30m", "coin_id": self.coin, "buy_at": 10, "sell_at": 70, "order": 27, "expected_time": "20 hours", "expected_percentage": "4%" },
      { "name": "Strategy 28", "rsi_type": "14", "rsi_time": "30m", "coin_id": self.coin, "buy_at": 30, "sell_at": 70, "order": 28, "expected_time": "20 hours", "expected_percentage": "4.5%" },
      { "name": "Strategy 29", "rsi_type": "14", "rsi_time": "30m", "coin_id": self.coin, "buy_at": 20, "sell_at": 70, "order": 29, "expected_time": "20 hours", "expected_percentage": "4.5%" },
      { "name": "Strategy 30", "rsi_type": "14", "rsi_time": "30m", "coin_id": self.coin, "buy_at": 10, "sell_at": 70, "order": 30, "expected_time": "20 hours", "expected_percentage": "4.5%" },
      { "name": "Strategy 31", "rsi_type": "6", "rsi_time": "1h", "coin_id": self.coin, "buy_at": 30, "sell_at": 70, "order": 31, "expected_time": "48 hours", "expected_percentage": "7%" },
      { "name": "Strategy 32", "rsi_type": "6", "rsi_time": "1h", "coin_id": self.coin, "buy_at": 20, "sell_at": 70, "order": 32, "expected_time": "48 hours", "expected_percentage": "7%" },
      { "name": "Strategy 33", "rsi_type": "6", "rsi_time": "1h", "coin_id": self.coin, "buy_at": 10, "sell_at": 70, "order": 33, "expected_time": "48 hours", "expected_percentage": "7%" },
      { "name": "Strategy 34", "rsi_type": "14", "rsi_time": "1h", "coin_id": self.coin, "buy_at": 30, "sell_at": 70, "order": 34, "expected_time": "48 hours", "expected_percentage": "10%" },
      { "name": "Strategy 35", "rsi_type": "14", "rsi_time": "1h", "coin_id": self.coin, "buy_at": 20, "sell_at": 70, "order": 35, "expected_time": "48 hours", "expected_percentage": "10%" },
      { "name": "Strategy 36", "rsi_type": "14", "rsi_time": "1h", "coin_id": self.coin, "buy_at": 10, "sell_at": 70, "order": 36, "expected_time": "48 hours", "expected_percentage": "10%" },
      { "name": "Strategy 37", "rsi_type": "6", "rsi_time": "2h", "coin_id": self.coin, "buy_at": 30, "sell_at": 70, "order": 37, "expected_time": "36 hours", "expected_percentage": "8%" },
      { "name": "Strategy 38", "rsi_type": "6", "rsi_time": "2h", "coin_id": self.coin, "buy_at": 20, "sell_at": 70, "order": 38, "expected_time": "36 hours", "expected_percentage": "8%" },
      { "name": "Strategy 39", "rsi_type": "6", "rsi_time": "2h", "coin_id": self.coin, "buy_at": 10, "sell_at": 70, "order": 39, "expected_time": "36 hours", "expected_percentage": "8%" },
      { "name": "Strategy 40", "rsi_type": "14", "rsi_time": "2h", "coin_id": self.coin, "buy_at": 30, "sell_at": 70, "order": 40, "expected_time": "36 hours", "expected_percentage": "12%" },
      { "name": "Strategy 41", "rsi_type": "14", "rsi_time": "2h", "coin_id": self.coin, "buy_at": 20, "sell_at": 70, "order": 41, "expected_time": "36 hours", "expected_percentage": "12%" },
      { "name": "Strategy 42", "rsi_type": "14", "rsi_time": "2h", "coin_id": self.coin, "buy_at": 10, "sell_at": 70, "order": 42, "expected_time": "36 hours", "expected_percentage": "12%" },
      { "name": "Strategy 43", "rsi_type": "6", "rsi_time": "4h", "coin_id": self.coin, "buy_at": 30, "sell_at": 70, "order": 43, "expected_time": "4 days", "expected_percentage": "10%" },
      { "name": "Strategy 44", "rsi_type": "6", "rsi_time": "4h", "coin_id": self.coin, "buy_at": 20, "sell_at": 70, "order": 44, "expected_time": "4 days", "expected_percentage": "10%" },
      { "name": "Strategy 45", "rsi_type": "6", "rsi_time": "4h", "coin_id": self.coin, "buy_at": 10, "sell_at": 70, "order": 45, "expected_time": "4 days", "expected_percentage": "10%" },
      { "name": "Strategy 46", "rsi_type": "14", "rsi_time": "4h", "coin_id": self.coin, "buy_at": 30, "sell_at": 70, "order": 46, "expected_time": "4 days", "expected_percentage": "15%" },
      { "name": "Strategy 47", "rsi_type": "14", "rsi_time": "4h", "coin_id": self.coin, "buy_at": 20, "sell_at": 70, "order": 47, "expected_time": "4 days", "expected_percentage": "15%" },
      { "name": "Strategy 48", "rsi_type": "14", "rsi_time": "4h", "coin_id": self.coin, "buy_at": 10, "sell_at": 70, "order": 48, "expected_time": "4 days", "expected_percentage": "15%" },
      { "name": "Strategy 49", "rsi_type": "6", "rsi_time": "6h", "coin_id": self.coin, "buy_at": 30, "sell_at": 70, "order": 49, "expected_time": "6 days", "expected_percentage": "12%" },
      { "name": "Strategy 50", "rsi_type": "6", "rsi_time": "6h", "coin_id": self.coin, "buy_at": 20, "sell_at": 70, "order": 50, "expected_time": "6 days", "expected_percentage": "12%" },
      { "name": "Strategy 51", "rsi_type": "6", "rsi_time": "6h", "coin_id": self.coin, "buy_at": 10, "sell_at": 70, "order": 51, "expected_time": "6 days", "expected_percentage": "12%" },
      { "name": "Strategy 52", "rsi_type": "14", "rsi_time": "6h", "coin_id": self.coin, "buy_at": 30, "sell_at": 70, "order": 52, "expected_time": "6 days", "expected_percentage": "15%" },
      { "name": "Strategy 53", "rsi_type": "14", "rsi_time": "6h", "coin_id": self.coin, "buy_at": 20, "sell_at": 70, "order": 53, "expected_time": "6 days", "expected_percentage": "15%" },
      { "name": "Strategy 54", "rsi_type": "14", "rsi_time": "6h", "coin_id": self.coin, "buy_at": 10, "sell_at": 70, "order": 54, "expected_time": "6 days", "expected_percentage": "15%" },
      { "name": "Strategy 55", "rsi_type": "6", "rsi_time": "8h", "coin_id": self.coin, "buy_at": 30, "sell_at": 70, "order": 55, "expected_time": "8 days", "expected_percentage": "12%" },
      { "name": "Strategy 56", "rsi_type": "6", "rsi_time": "8h", "coin_id": self.coin, "buy_at": 20, "sell_at": 70, "order": 56, "expected_time": "8 days", "expected_percentage": "12%" },
      { "name": "Strategy 57", "rsi_type": "6", "rsi_time": "8h", "coin_id": self.coin, "buy_at": 10, "sell_at": 70, "order": 57, "expected_time": "8 days", "expected_percentage": "12%" },
      { "name": "Strategy 58", "rsi_type": "14", "rsi_time": "8h", "coin_id": self.coin, "buy_at": 30, "sell_at": 70, "order": 58, "expected_time": "8 days", "expected_percentage": "15%" },
      { "name": "Strategy 59", "rsi_type": "14", "rsi_time": "8h", "coin_id": self.coin, "buy_at": 20, "sell_at": 70, "order": 59, "expected_time": "8 days", "expected_percentage": "15%" },
      { "name": "Strategy 60", "rsi_type": "14", "rsi_time": "8h", "coin_id": self.coin, "buy_at": 10, "sell_at": 70, "order": 60, "expected_time": "8 days", "expected_percentage": "15%" },
      { "name": "Strategy 61", "rsi_type": "6", "rsi_time": "12h", "coin_id": self.coin, "buy_at": 30, "sell_at": 70, "order": 61, "expected_time": "12 days", "expected_percentage": "15%" },
      { "name": "Strategy 62", "rsi_type": "6", "rsi_time": "12h", "coin_id": self.coin, "buy_at": 20, "sell_at": 70, "order": 62, "expected_time": "12 days", "expected_percentage": "15%" },
      { "name": "Strategy 63", "rsi_type": "6", "rsi_time": "12h", "coin_id": self.coin, "buy_at": 10, "sell_at": 70, "order": 63, "expected_time": "12 days", "expected_percentage": "15%" },
      { "name": "Strategy 64", "rsi_type": "14", "rsi_time": "12h", "coin_id": self.coin, "buy_at": 30, "sell_at": 70, "order": 64, "expected_time": "12 days", "expected_percentage": "18%" },
      { "name": "Strategy 65", "rsi_type": "14", "rsi_time": "12h", "coin_id": self.coin, "buy_at": 20, "sell_at": 70, "order": 65, "expected_time": "12 days", "expected_percentage": "18%" },
      { "name": "Strategy 66", "rsi_type": "14", "rsi_time": "12h", "coin_id": self.coin, "buy_at": 10, "sell_at": 70, "order": 66, "expected_time": "12 days", "expected_percentage": "18%" },
      { "name": "Strategy 67", "rsi_type": "6", "rsi_time": "1d", "coin_id": self.coin, "buy_at": 30, "sell_at": 70, "order": 67, "expected_time": "15 days", "expected_percentage": "20%" },
      { "name": "Strategy 68", "rsi_type": "6", "rsi_time": "1d", "coin_id": self.coin, "buy_at": 20, "sell_at": 70, "order": 68, "expected_time": "15 days", "expected_percentage": "20%" },
      { "name": "Strategy 69", "rsi_type": "6", "rsi_time": "1d", "coin_id": self.coin, "buy_at": 10, "sell_at": 70, "order": 69, "expected_time": "15 days", "expected_percentage": "20%" },
      { "name": "Strategy 70", "rsi_type": "14", "rsi_time": "1d", "coin_id": self.coin, "buy_at": 30, "sell_at": 70, "order": 70, "expected_time": "1 month", "expected_percentage": "25%" },
      { "name": "Strategy 71", "rsi_type": "14", "rsi_time": "1d", "coin_id": self.coin, "buy_at": 20, "sell_at": 70, "order": 71, "expected_time": "1 month", "expected_percentage": "25%" },
      { "name": "Strategy 72", "rsi_type": "14", "rsi_time": "1d", "coin_id": self.coin, "buy_at": 10, "sell_at": 70, "order": 72, "expected_time": "1 month", "expected_percentage": "25%" },
      { "name": "Strategy 73", "rsi_type": "6", "rsi_time": "3d", "coin_id": self.coin, "buy_at": 30, "sell_at": 70, "order": 73, "expected_time": "1 month", "expected_percentage": "25%" },
      { "name": "Strategy 74", "rsi_type": "6", "rsi_time": "3d", "coin_id": self.coin, "buy_at": 20, "sell_at": 70, "order": 74, "expected_time": "1 month", "expected_percentage": "25%" },
      { "name": "Strategy 75", "rsi_type": "6", "rsi_time": "3d", "coin_id": self.coin, "buy_at": 10, "sell_at": 70, "order": 75, "expected_time": "1 month", "expected_percentage": "25%" },
      { "name": "Strategy 76", "rsi_type": "14", "rsi_time": "3d", "coin_id": self.coin, "buy_at": 30, "sell_at": 70, "order": 76, "expected_time": "1.5 month", "expected_percentage": "30%" },
      { "name": "Strategy 77", "rsi_type": "14", "rsi_time": "3d", "coin_id": self.coin, "buy_at": 20, "sell_at": 70, "order": 77, "expected_time": "1.5 month", "expected_percentage": "30%" },
      { "name": "Strategy 78", "rsi_type": "14", "rsi_time": "3d", "coin_id": self.coin, "buy_at": 10, "sell_at": 70, "order": 78, "expected_time": "1.5 month", "expected_percentage": "30%" },
      { "name": "Strategy 79", "rsi_type": "6", "rsi_time": "1w", "coin_id": self.coin, "buy_at": 30, "sell_at": 70, "order": 79, "expected_time": "6 months", "expected_percentage": "100%" },
      { "name": "Strategy 80", "rsi_type": "6", "rsi_time": "1w", "coin_id": self.coin, "buy_at": 20, "sell_at": 70, "order": 80, "expected_time": "6 months", "expected_percentage": "100%" },
      { "name": "Strategy 81", "rsi_type": "6", "rsi_time": "1w", "coin_id": self.coin, "buy_at": 10, "sell_at": 70, "order": 81, "expected_time": "6 months", "expected_percentage": "100%" },
      { "name": "Strategy 82", "rsi_type": "14", "rsi_time": "1w", "coin_id": self.coin, "buy_at": 30, "sell_at": 70, "order": 82, "expected_time": "1 year", "expected_percentage": "150%" },
      { "name": "Strategy 83", "rsi_type": "14", "rsi_time": "1w", "coin_id": self.coin, "buy_at": 20, "sell_at": 70, "order": 83, "expected_time": "1 year", "expected_percentage": "150%" },
      { "name": "Strategy 84", "rsi_type": "14", "rsi_time": "1w", "coin_id": self.coin, "buy_at": 10, "sell_at": 70, "order": 84, "expected_time": "1 year", "expected_percentage": "150%" },
      { "name": "Strategy 85", "rsi_type": "6", "rsi_time": "1M", "coin_id": self.coin, "buy_at": 30, "sell_at": 70, "order": 85, "expected_time": "1 year", "expected_percentage": "150%" },
      { "name": "Strategy 86", "rsi_type": "6", "rsi_time": "1M", "coin_id": self.coin, "buy_at": 20, "sell_at": 70, "order": 86, "expected_time": "1 year", "expected_percentage": "150%" },
      { "name": "Strategy 87", "rsi_type": "6", "rsi_time": "1M", "coin_id": self.coin, "buy_at": 10, "sell_at": 70, "order": 87, "expected_time": "1 year", "expected_percentage": "150%" },
      { "name": "Strategy 88", "rsi_type": "14", "rsi_time": "1M", "coin_id": self.coin, "buy_at": 30, "sell_at": 70, "order": 88, "expected_time": "15.2 years", "expected_percentage": "200%" },
      { "name": "Strategy 89", "rsi_type": "14", "rsi_time": "1M", "coin_id": self.coin, "buy_at": 20, "sell_at": 70, "order": 89, "expected_time": "15.2 years", "expected_percentage": "200%" },
      { "name": "Strategy 90", "rsi_type": "14", "rsi_time": "1M", "coin_id": self.coin, "buy_at": 10, "sell_at": 70, "order": 90, "expected_time": "15.2 years", "expected_percentage": "200%" }
    ]
