from api.models import Strategy

class StrategyCreator:
  def __init__(self, coin, **kwargs):
    self.coin = coin

  def create(self):
    for strategy_data in self.__strategy_list():
      Strategy.objects.create(**strategy_data)

  def __strategy_list(self):
    return [
      { "name": "Strategy 1", "rsi_type": "6", "rsi_time": "1m", "coin_id": self.coin, "buy_at": 30, "sell_at": 70},
      { "name": "Strategy 2", "rsi_type": "6", "rsi_time": "1m", "coin_id": self.coin, "buy_at": 20, "sell_at": 70},
      { "name": "Strategy 3", "rsi_type": "6", "rsi_time": "1m", "coin_id": self.coin, "buy_at": 10, "sell_at": 70},
      { "name": "Strategy 4", "rsi_type": "14", "rsi_time": "1m", "coin_id": self.coin, "buy_at": 30, "sell_at": 70 },
      { "name": "Strategy 5", "rsi_type": "14", "rsi_time": "1m", "coin_id": self.coin, "buy_at": 20, "sell_at": 70 },
      { "name": "Strategy 6", "rsi_type": "14", "rsi_time": "1m", "coin_id": self.coin, "buy_at": 10, "sell_at": 70 },
      { "name": "Strategy 7", "rsi_type": "6", "rsi_time": "3m", "coin_id": self.coin, "buy_at": 30, "sell_at": 70 },
      { "name": "Strategy 8", "rsi_type": "6", "rsi_time": "3m", "coin_id": self.coin, "buy_at": 20, "sell_at": 70 },
      { "name": "Strategy 9", "rsi_type": "6", "rsi_time": "3m", "coin_id": self.coin, "buy_at": 10, "sell_at": 70 },
      { "name": "Strategy 10", "rsi_type": "14", "rsi_time": "3m", "coin_id": self.coin, "buy_at": 30, "sell_at": 70 },
      { "name": "Strategy 11", "rsi_type": "14", "rsi_time": "3m", "coin_id": self.coin, "buy_at": 20, "sell_at": 70 },
      { "name": "Strategy 12", "rsi_type": "14", "rsi_time": "3m", "coin_id": self.coin, "buy_at": 10, "sell_at": 70 },
      { "name": "Strategy 13", "rsi_type": "6", "rsi_time": "5m", "coin_id": self.coin, "buy_at": 30, "sell_at": 70 },
      { "name": "Strategy 14", "rsi_type": "6", "rsi_time": "5m", "coin_id": self.coin, "buy_at": 20, "sell_at": 70 },
      { "name": "Strategy 15", "rsi_type": "6", "rsi_time": "5m", "coin_id": self.coin, "buy_at": 10, "sell_at": 70 },
      { "name": "Strategy 16", "rsi_type": "14", "rsi_time": "5m", "coin_id": self.coin, "buy_at": 30, "sell_at": 70 },
      { "name": "Strategy 17", "rsi_type": "14", "rsi_time": "5m", "coin_id": self.coin, "buy_at": 20, "sell_at": 70 },
      { "name": "Strategy 18", "rsi_type": "14", "rsi_time": "5m", "coin_id": self.coin, "buy_at": 10, "sell_at": 70 },
      { "name": "Strategy 19", "rsi_type": "6", "rsi_time": "15m", "coin_id": self.coin, "buy_at": 30, "sell_at": 70 },
      { "name": "Strategy 20", "rsi_type": "6", "rsi_time": "15m", "coin_id": self.coin, "buy_at": 20, "sell_at": 70 },
      { "name": "Strategy 21", "rsi_type": "6", "rsi_time": "15m", "coin_id": self.coin, "buy_at": 10, "sell_at": 70 },
      { "name": "Strategy 22", "rsi_type": "14", "rsi_time": "15m", "coin_id": self.coin, "buy_at": 30, "sell_at": 70 },
      { "name": "Strategy 23", "rsi_type": "14", "rsi_time": "15m", "coin_id": self.coin, "buy_at": 20, "sell_at": 70 },
      { "name": "Strategy 24", "rsi_type": "14", "rsi_time": "15m", "coin_id": self.coin, "buy_at": 10, "sell_at": 70 },
      { "name": "Strategy 25", "rsi_type": "6", "rsi_time": "30m", "coin_id": self.coin, "buy_at": 30, "sell_at": 70 },
      { "name": "Strategy 26", "rsi_type": "6", "rsi_time": "30m", "coin_id": self.coin, "buy_at": 20, "sell_at": 70 },
      { "name": "Strategy 27", "rsi_type": "6", "rsi_time": "30m", "coin_id": self.coin, "buy_at": 10, "sell_at": 70 },
      { "name": "Strategy 28", "rsi_type": "14", "rsi_time": "30m", "coin_id": self.coin, "buy_at": 30, "sell_at": 70 },
      { "name": "Strategy 29", "rsi_type": "14", "rsi_time": "30m", "coin_id": self.coin, "buy_at": 20, "sell_at": 70 },
      { "name": "Strategy 30", "rsi_type": "14", "rsi_time": "30m", "coin_id": self.coin, "buy_at": 10, "sell_at": 70 },
      { "name": "Strategy 31", "rsi_type": "6", "rsi_time": "1h", "coin_id": self.coin, "buy_at": 30, "sell_at": 70 },
      { "name": "Strategy 32", "rsi_type": "6", "rsi_time": "1h", "coin_id": self.coin, "buy_at": 20, "sell_at": 70 },
      { "name": "Strategy 33", "rsi_type": "6", "rsi_time": "1h", "coin_id": self.coin, "buy_at": 10, "sell_at": 70 },
      { "name": "Strategy 34", "rsi_type": "14", "rsi_time": "1h", "coin_id": self.coin, "buy_at": 30, "sell_at": 70 },
      { "name": "Strategy 35", "rsi_type": "14", "rsi_time": "1h", "coin_id": self.coin, "buy_at": 20, "sell_at": 70 },
      { "name": "Strategy 36", "rsi_type": "14", "rsi_time": "1h", "coin_id": self.coin, "buy_at": 10, "sell_at": 70 },
      { "name": "Strategy 37", "rsi_type": "6", "rsi_time": "2h", "coin_id": self.coin, "buy_at": 30, "sell_at": 70 },
      { "name": "Strategy 38", "rsi_type": "6", "rsi_time": "2h", "coin_id": self.coin, "buy_at": 20, "sell_at": 70 },
      { "name": "Strategy 39", "rsi_type": "6", "rsi_time": "2h", "coin_id": self.coin, "buy_at": 10, "sell_at": 70 },
      { "name": "Strategy 40", "rsi_type": "14", "rsi_time": "2h", "coin_id": self.coin, "buy_at": 30, "sell_at": 70 },
      { "name": "Strategy 41", "rsi_type": "14", "rsi_time": "2h", "coin_id": self.coin, "buy_at": 20, "sell_at": 70 },
      { "name": "Strategy 42", "rsi_type": "14", "rsi_time": "2h", "coin_id": self.coin, "buy_at": 10, "sell_at": 70 },
      { "name": "Strategy 43", "rsi_type": "6", "rsi_time": "4h", "coin_id": self.coin, "buy_at": 30, "sell_at": 70 },
      { "name": "Strategy 44", "rsi_type": "6", "rsi_time": "4h", "coin_id": self.coin, "buy_at": 20, "sell_at": 70 },
      { "name": "Strategy 45", "rsi_type": "6", "rsi_time": "4h", "coin_id": self.coin, "buy_at": 10, "sell_at": 70 },
      { "name": "Strategy 46", "rsi_type": "14", "rsi_time": "4h", "coin_id": self.coin, "buy_at": 30, "sell_at": 70 },
      { "name": "Strategy 47", "rsi_type": "14", "rsi_time": "4h", "coin_id": self.coin, "buy_at": 20, "sell_at": 70 },
      { "name": "Strategy 48", "rsi_type": "14", "rsi_time": "4h", "coin_id": self.coin, "buy_at": 10, "sell_at": 70 },
      { "name": "Strategy 49", "rsi_type": "6", "rsi_time": "6h", "coin_id": self.coin, "buy_at": 30, "sell_at": 70 },
      { "name": "Strategy 50", "rsi_type": "6", "rsi_time": "6h", "coin_id": self.coin, "buy_at": 20, "sell_at": 70 },
      { "name": "Strategy 51", "rsi_type": "6", "rsi_time": "6h", "coin_id": self.coin, "buy_at": 10, "sell_at": 70 },
      { "name": "Strategy 52", "rsi_type": "14", "rsi_time": "6h", "coin_id": self.coin, "buy_at": 30, "sell_at": 70 },
      { "name": "Strategy 53", "rsi_type": "14", "rsi_time": "6h", "coin_id": self.coin, "buy_at": 20, "sell_at": 70 },
      { "name": "Strategy 54", "rsi_type": "14", "rsi_time": "6h", "coin_id": self.coin, "buy_at": 10, "sell_at": 70 },
      { "name": "Strategy 55", "rsi_type": "6", "rsi_time": "8h", "coin_id": self.coin, "buy_at": 30, "sell_at": 70 },
      { "name": "Strategy 56", "rsi_type": "6", "rsi_time": "8h", "coin_id": self.coin, "buy_at": 20, "sell_at": 70 },
      { "name": "Strategy 57", "rsi_type": "6", "rsi_time": "8h", "coin_id": self.coin, "buy_at": 10, "sell_at": 70 },
      { "name": "Strategy 58", "rsi_type": "14", "rsi_time": "8h", "coin_id": self.coin, "buy_at": 30, "sell_at": 70 },
      { "name": "Strategy 59", "rsi_type": "14", "rsi_time": "8h", "coin_id": self.coin, "buy_at": 20, "sell_at": 70 },
      { "name": "Strategy 60", "rsi_type": "14", "rsi_time": "8h", "coin_id": self.coin, "buy_at": 10, "sell_at": 70 },
      { "name": "Strategy 61", "rsi_type": "6", "rsi_time": "12h", "coin_id": self.coin, "buy_at": 30, "sell_at": 70 },
      { "name": "Strategy 62", "rsi_type": "6", "rsi_time": "12h", "coin_id": self.coin, "buy_at": 20, "sell_at": 70 },
      { "name": "Strategy 63", "rsi_type": "6", "rsi_time": "12h", "coin_id": self.coin, "buy_at": 10, "sell_at": 70 },
      { "name": "Strategy 64", "rsi_type": "14", "rsi_time": "12h", "coin_id": self.coin, "buy_at": 30, "sell_at": 70 },
      { "name": "Strategy 65", "rsi_type": "14", "rsi_time": "12h", "coin_id": self.coin, "buy_at": 20, "sell_at": 70 },
      { "name": "Strategy 66", "rsi_type": "14", "rsi_time": "12h", "coin_id": self.coin, "buy_at": 10, "sell_at": 70 },
      { "name": "Strategy 67", "rsi_type": "6", "rsi_time": "1d", "coin_id": self.coin, "buy_at": 30, "sell_at": 70 },
      { "name": "Strategy 68", "rsi_type": "6", "rsi_time": "1d", "coin_id": self.coin, "buy_at": 20, "sell_at": 70 },
      { "name": "Strategy 69", "rsi_type": "6", "rsi_time": "1d", "coin_id": self.coin, "buy_at": 10, "sell_at": 70 },
      { "name": "Strategy 70", "rsi_type": "14", "rsi_time": "1d", "coin_id": self.coin, "buy_at": 30, "sell_at": 70 },
      { "name": "Strategy 71", "rsi_type": "14", "rsi_time": "1d", "coin_id": self.coin, "buy_at": 20, "sell_at": 70 },
      { "name": "Strategy 72", "rsi_type": "14", "rsi_time": "1d", "coin_id": self.coin, "buy_at": 10, "sell_at": 70 },
      { "name": "Strategy 73", "rsi_type": "6", "rsi_time": "3d", "coin_id": self.coin, "buy_at": 30, "sell_at": 70 },
      { "name": "Strategy 74", "rsi_type": "6", "rsi_time": "3d", "coin_id": self.coin, "buy_at": 20, "sell_at": 70 },
      { "name": "Strategy 75", "rsi_type": "6", "rsi_time": "3d", "coin_id": self.coin, "buy_at": 10, "sell_at": 70 },
      { "name": "Strategy 76", "rsi_type": "14", "rsi_time": "3d", "coin_id": self.coin, "buy_at": 30, "sell_at": 70 },
      { "name": "Strategy 77", "rsi_type": "14", "rsi_time": "3d", "coin_id": self.coin, "buy_at": 20, "sell_at": 70 },
      { "name": "Strategy 78", "rsi_type": "14", "rsi_time": "3d", "coin_id": self.coin, "buy_at": 10, "sell_at": 70 },
      { "name": "Strategy 79", "rsi_type": "6", "rsi_time": "1w", "coin_id": self.coin, "buy_at": 30, "sell_at": 70 },
      { "name": "Strategy 80", "rsi_type": "6", "rsi_time": "1w", "coin_id": self.coin, "buy_at": 20, "sell_at": 70 },
      { "name": "Strategy 81", "rsi_type": "6", "rsi_time": "1w", "coin_id": self.coin, "buy_at": 10, "sell_at": 70 },
      { "name": "Strategy 82", "rsi_type": "14", "rsi_time": "1w", "coin_id": self.coin, "buy_at": 30, "sell_at": 70 },
      { "name": "Strategy 83", "rsi_type": "14", "rsi_time": "1w", "coin_id": self.coin, "buy_at": 20, "sell_at": 70 },
      { "name": "Strategy 84", "rsi_type": "14", "rsi_time": "1w", "coin_id": self.coin, "buy_at": 10, "sell_at": 70 },
      { "name": "Strategy 85", "rsi_type": "6", "rsi_time": "1M", "coin_id": self.coin, "buy_at": 30, "sell_at": 70 },
      { "name": "Strategy 86", "rsi_type": "6", "rsi_time": "1M", "coin_id": self.coin, "buy_at": 20, "sell_at": 70 },
      { "name": "Strategy 87", "rsi_type": "6", "rsi_time": "1M", "coin_id": self.coin, "buy_at": 10, "sell_at": 70 },
      { "name": "Strategy 88", "rsi_type": "14", "rsi_time": "1M", "coin_id": self.coin, "buy_at": 30, "sell_at": 70 },
      { "name": "Strategy 89", "rsi_type": "14", "rsi_time": "1M", "coin_id": self.coin, "buy_at": 20, "sell_at": 70 },
      { "name": "Strategy 90", "rsi_type": "14", "rsi_time": "1M", "coin_id": self.coin, "buy_at": 10, "sell_at": 70 }
    ]
