# Generated by Django 3.2.25 on 2024-07-05 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('rsi_type', models.IntegerField(max_length=3)),
                ('coin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to='api.coin')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('client_secret', models.CharField(max_length=100)),
                ('client_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserStrategy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=True)),
                ('strategy_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_strategies', to='api.strategy')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_strategies', to='api.user')),
            ],
        ),
    ]
