# Generated by Django 3.2.25 on 2024-07-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20240721_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstrategy',
            name='purchased',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userstrategy',
            name='purchased_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='userstrategy',
            name='sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userstrategy',
            name='sale_at',
            field=models.DateTimeField(null=True),
        ),
    ]
