# Generated by Django 3.2.25 on 2024-08-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20240721_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='min_value',
            field=models.FloatField(default=0, null=True),
        ),
    ]
