# Generated by Django 3.2.25 on 2024-09-23 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_coin_min_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='password@123', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='client_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='client_secret',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
