# Generated by Django 3.2.25 on 2024-10-07 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20240930_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='recommended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='strategy',
            name='recommended',
            field=models.BooleanField(default=False),
        ),
    ]
