# Generated by Django 3.2.25 on 2024-11-05 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20241007_0658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstrategy',
            name='sale',
        ),
        migrations.RemoveField(
            model_name='userstrategy',
            name='sale_at',
        ),
    ]
