# Generated by Django 3.2.25 on 2024-11-21 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20241105_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
    ]
