# Generated by Django 3.2.25 on 2024-09-25 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20240924_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='payment_receipt_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
