# Generated by Django 3.2.25 on 2024-11-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_coin_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='asset',
            field=models.CharField(default='USDT', max_length=50),
        ),
        migrations.AddField(
            model_name='coin',
            name='base_name',
            field=models.CharField(default='W', max_length=50),
        ),
    ]
