# Generated by Django 3.2.25 on 2024-09-27 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20240925_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='buy_at',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='strategy',
            name='sell_at',
            field=models.IntegerField(default=70),
        ),
        migrations.AddConstraint(
            model_name='strategy',
            constraint=models.UniqueConstraint(fields=('name', 'coin_id'), name='unique_name_coin_id'),
        ),
        migrations.AddConstraint(
            model_name='userstrategy',
            constraint=models.UniqueConstraint(fields=('user_id', 'strategy_id'), name='unique_user_strategy_id'),
        ),
    ]
