# Generated by Django 3.2.25 on 2024-09-30 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_merge_0006_auto_20240923_1603_0010_auto_20240927_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
    ]
