# Generated by Django 4.2.16 on 2024-12-17 22:18

from django.db import migrations

def populate_order_in_strategies(apps, schema_editor):
    Strategy = apps.get_model('api', 'Strategy')

    for i in range(1, 91):
        Strategy.objects.filter(name=f"Strategy {i}").update(order=i)

def reverse_populate_order_in_strategies(apps, schema_editor):
    Strategy = apps.get_model('api', 'Strategy')
    Strategy.objects.update(order=None)

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_userstrategy_options_strategy_order_and_more'),
    ]

    operations = [
       migrations.RunPython(populate_order_in_strategies, reverse_populate_order_in_strategies),
    ]
