# Generated by Django 4.2.16 on 2024-12-18 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20241217_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstrategy',
            name='purchased',
        ),
        migrations.RemoveField(
            model_name='userstrategy',
            name='purchased_at',
        ),
    ]
