# Generated by Django 3.2.25 on 2025-01-29 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20250125_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='bottom_value',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=10),
        ),
    ]
