# Generated by Django 5.1.6 on 2025-02-18 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_user_wallet_address_alter_coin_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='expected_percentage',
            field=models.CharField(default='0.25%', max_length=20),
        ),
        migrations.AddField(
            model_name='strategy',
            name='expected_time',
            field=models.CharField(default='1 hours', max_length=20),
        ),
    ]
