# Generated by Django 5.1.6 on 2025-02-18 02:43

from django.db import migrations

def updateStrategies(apps, schema_editor):
    from api.services.strategy_creator import StrategyCreator
    Strategy = apps.get_model('api', 'Strategy')
    Coin = apps.get_model('api', 'Coin')
    strategy_list = StrategyCreator(Coin.objects.first()).strategy_list()

    for strategy_item in strategy_list:
        Strategy.objects.filter(rsi_time=strategy_item['rsi_time'], rsi_type=strategy_item['rsi_type']).update(expected_time=strategy_item['expected_time'], expected_percentage=strategy_item['expected_percentage'])

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_strategy_expected_percentage_strategy_expected_time_and_more'),
    ]

    operations = [
        migrations.RunPython(updateStrategies, reverse_code=migrations.RunPython.noop),
    ]
