# Generated by Django 5.1.6 on 2025-02-24 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20250218_0754'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCoin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('auto_recommended', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='usercoin',
            name='coin_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_coins', to='api.coin'),
        ),
        migrations.AddField(
            model_name='usercoin',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_coins', to=settings.AUTH_USER_MODEL),
        ),
    ]
