# Generated by Django 5.1.6 on 2025-03-13 16:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_coin_name_alter_strategy_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='limited_trades',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='strategy',
            name='max_trades',
            field=models.IntegerField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='userstrategy',
            name='no_of_trades',
            field=models.IntegerField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='userstrategy',
            name='amount',
            field=models.FloatField(default=10.0, validators=[django.core.validators.MinValueValidator(10.0)]),
        ),
    ]
