# Generated by Django 5.1.6 on 2025-03-14 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_strategy_limited_trades_strategy_max_trades_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='max_trades',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userstrategy',
            name='no_of_trades',
            field=models.IntegerField(default=0),
        ),
    ]
