# Generated by Django 5.1.6 on 2025-05-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_subscription_alter_coin_name_alter_strategy_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_active_subscription',
            field=models.BooleanField(default=False),
        )
    ]
