# Generated by Django 3.2.25 on 2024-08-01 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0003_auto_20240721_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, max_length=10, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('order_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=5)),
                ('price_unit', models.CharField(blank=True, max_length=10, null=True)),
                ('quantity', models.CharField(blank=True, max_length=10, null=True)),
                ('commission', models.CharField(blank=True, max_length=10, null=True)),
                ('external_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userstrategy')),
            ],
        ),
    ]
