# Generated by Django 3.2.25 on 2024-08-05 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20240804_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buy_order', to='bot.order'),
        ),
    ]
